# Generated by Django 3.2.23 on 2024-01-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='marked',
            field=models.BooleanField(default=False, verbose_name='Помечен на удаление'),
        ),
        migrations.AddField(
            model_name='order',
            name='posted',
            field=models.BooleanField(default=False, verbose_name='Проведен'),
        ),
    ]
