# Generated by Django 3.2.23 on 2024-01-22 04:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_auto_20240120_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('marked', models.BooleanField(default=False, verbose_name='Помечен на удаление')),
                ('name', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Наименование')),
                ('address1', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Адрес')),
                ('address2', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Адрес')),
                ('address3', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Адрес')),
                ('phone1', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Телефон')),
                ('phone2', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Телефон')),
                ('phone3', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Телефон')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_address',
            field=models.CharField(default='', max_length=255, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(default='', max_length=150, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_phone',
            field=models.CharField(default='', max_length=25, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='order',
            name='sender_address',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='order',
            name='sender_name',
            field=models.CharField(default='', max_length=150, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='order',
            name='sender_phone',
            field=models.CharField(default='', max_length=25, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipient', to='order_app.contractor', verbose_name='Получатель'),
        ),
        migrations.AddField(
            model_name='order',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sender', to='order_app.contractor', verbose_name='Отправитель'),
        ),
    ]
