# Generated by Django 3.2.23 on 2024-03-31 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0004_auto_20240122_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 31, 19, 11, 44, 555794), null=True, verbose_name='Дата'),
        ),
    ]
