# Generated by Django 3.2.23 on 2024-01-20 09:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('name', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Наименование')),
                ('width', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Ширина, см')),
                ('height', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Высота, см')),
                ('length', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Длина, см')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Вес, кг')),
                ('volume', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Объем, м3')),
                ('description', models.CharField(max_length=150, verbose_name='Описание')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargoes', to='order_app.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Груз',
                'verbose_name_plural': 'Грузы',
            },
        ),
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('number', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Номер')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Moving',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('number', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Номер')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Outgoing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('number', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Номер')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('name', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Место хранения',
                'verbose_name_plural': 'Места хранения',
            },
        ),
        migrations.CreateModel(
            name='OutgoingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('number', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Номер')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse_app.cargo')),
                ('outgoing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse_app.outgoing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('number', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Номер')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse_app.cargo')),
                ('moving', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse_app.moving')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncomingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('number', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Номер')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse_app.cargo')),
                ('incoming', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse_app.incoming')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
