# Generated by Django 3.2.23 on 2024-01-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incoming',
            options={'ordering': ['-number'], 'verbose_name': 'Приходный ордер', 'verbose_name_plural': 'Приходные ордера'},
        ),
        migrations.AlterModelOptions(
            name='moving',
            options={'ordering': ['-number'], 'verbose_name': 'Перемещение', 'verbose_name_plural': 'Перемещения'},
        ),
        migrations.AlterModelOptions(
            name='outgoing',
            options={'ordering': ['-number'], 'verbose_name': 'Расходный ордер', 'verbose_name_plural': 'Расходные ордера'},
        ),
        migrations.RemoveField(
            model_name='incomingitem',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='incomingitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='incomingitem',
            name='date',
        ),
        migrations.RemoveField(
            model_name='incomingitem',
            name='number',
        ),
        migrations.RemoveField(
            model_name='incomingitem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='movingitem',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='movingitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='movingitem',
            name='date',
        ),
        migrations.RemoveField(
            model_name='movingitem',
            name='number',
        ),
        migrations.RemoveField(
            model_name='movingitem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='outgoingitem',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='outgoingitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='outgoingitem',
            name='date',
        ),
        migrations.RemoveField(
            model_name='outgoingitem',
            name='number',
        ),
        migrations.RemoveField(
            model_name='outgoingitem',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='incomingitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movingitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='outgoingitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
