# Generated by Django 3.2.23 on 2024-01-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0002_auto_20240120_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='type',
            field=models.CharField(choices=[('CA', 'Контрагент (юридическое лицо, сторонний контрагент, подрядчик)'), ('WH', 'Склад (адрес, помещение)'), ('WH', 'Сотрудник (курьер, экспедитор)')], default='WH', max_length=2, verbose_name='Заказ'),
        ),
    ]
