# Generated by Django 3.2.23 on 2024-01-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0003_warehouse_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='type',
            field=models.CharField(choices=[('CA', 'Контрагент (юридическое лицо, сторонний контрагент, подрядчик)'), ('WH', 'Склад (адрес, помещение)'), ('WH', 'Сотрудник (курьер, экспедитор)')], default='WH', max_length=2, verbose_name='Тип'),
        ),
    ]
