# Generated by Django 3.2.23 on 2024-01-20 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0004_alter_warehouse_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='incoming',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse_app.warehouse', verbose_name='Получатель'),
        ),
        migrations.AddField(
            model_name='moving',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipient', to='warehouse_app.warehouse', verbose_name='Получатель'),
        ),
        migrations.AddField(
            model_name='moving',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sender', to='warehouse_app.warehouse', verbose_name='Отправитель'),
        ),
        migrations.AddField(
            model_name='outgoing',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse_app.warehouse', verbose_name='Отправитель'),
        ),
    ]
