# Generated by Django 3.2.23 on 2024-01-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0005_auto_20240120_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='marked',
            field=models.BooleanField(default=False, verbose_name='Помечен на удаление'),
        ),
        migrations.AddField(
            model_name='incoming',
            name='marked',
            field=models.BooleanField(default=False, verbose_name='Помечен на удаление'),
        ),
        migrations.AddField(
            model_name='incoming',
            name='posted',
            field=models.BooleanField(default=False, verbose_name='Проведен'),
        ),
        migrations.AddField(
            model_name='moving',
            name='marked',
            field=models.BooleanField(default=False, verbose_name='Помечен на удаление'),
        ),
        migrations.AddField(
            model_name='moving',
            name='posted',
            field=models.BooleanField(default=False, verbose_name='Проведен'),
        ),
        migrations.AddField(
            model_name='outgoing',
            name='marked',
            field=models.BooleanField(default=False, verbose_name='Помечен на удаление'),
        ),
        migrations.AddField(
            model_name='outgoing',
            name='posted',
            field=models.BooleanField(default=False, verbose_name='Проведен'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='marked',
            field=models.BooleanField(default=False, verbose_name='Помечен на удаление'),
        ),
    ]
