# Generated by Django 3.2.23 on 2024-01-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0007_auto_20240120_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargoregistry',
            options={'verbose_name': 'Движение груза', 'verbose_name_plural': 'Движения грузов'},
        ),
        migrations.AddField(
            model_name='cargoregistry',
            name='type',
            field=models.CharField(choices=[('INC', 'Увеличение (приход)'), ('DEC', 'Уменьшение (расход)')], default='INC', max_length=3, verbose_name='Тип'),
        ),
    ]
