# Generated by Django 3.2.23 on 2024-03-31 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0008_auto_20240122_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 31, 19, 11, 44, 555794), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='moving',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 31, 19, 11, 44, 555794), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='outgoing',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 31, 19, 11, 44, 555794), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='type',
            field=models.CharField(choices=[('CA', 'Контрагент (юридическое лицо, сторонний контрагент, подрядчик)'), ('WH', 'Склад (адрес, помещение)'), ('EM', 'Сотрудник (курьер, экспедитор)')], default='WH', max_length=2, verbose_name='Тип'),
        ),
    ]
